// Copyright (c) 2023 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.9
// source: service.proto

package serviceextension

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Service_JoinMatch_FullMethodName          = "/service.Service/JoinMatch"
	Service_GetMatchState_FullMethodName      = "/service.Service/GetMatchState"
	Service_SubmitMatchCommand_FullMethodName = "/service.Service/SubmitMatchCommand"
)

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	// JoinMatch creates the authoritative match from the fixed AGS Session
	// roster when necessary, assigns stable seats, and returns only the
	// authenticated caller's view.
	JoinMatch(ctx context.Context, in *JoinMatchRequest, opts ...grpc.CallOption) (*JoinMatchResponse, error)
	// GetMatchState returns a caller-specific projection. Concealed tiles and
	// private claim responses belonging to other players are never included.
	GetMatchState(ctx context.Context, in *GetMatchStateRequest, opts ...grpc.CallOption) (*GetMatchStateResponse, error)
	// SubmitMatchCommand applies one idempotent player command after validating
	// Session membership, seat ownership, turn ownership, and state version.
	SubmitMatchCommand(ctx context.Context, in *SubmitMatchCommandRequest, opts ...grpc.CallOption) (*SubmitMatchCommandResponse, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) JoinMatch(ctx context.Context, in *JoinMatchRequest, opts ...grpc.CallOption) (*JoinMatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinMatchResponse)
	err := c.cc.Invoke(ctx, Service_JoinMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetMatchState(ctx context.Context, in *GetMatchStateRequest, opts ...grpc.CallOption) (*GetMatchStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMatchStateResponse)
	err := c.cc.Invoke(ctx, Service_GetMatchState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) SubmitMatchCommand(ctx context.Context, in *SubmitMatchCommandRequest, opts ...grpc.CallOption) (*SubmitMatchCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitMatchCommandResponse)
	err := c.cc.Invoke(ctx, Service_SubmitMatchCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations should embed UnimplementedServiceServer
// for forward compatibility.
type ServiceServer interface {
	// JoinMatch creates the authoritative match from the fixed AGS Session
	// roster when necessary, assigns stable seats, and returns only the
	// authenticated caller's view.
	JoinMatch(context.Context, *JoinMatchRequest) (*JoinMatchResponse, error)
	// GetMatchState returns a caller-specific projection. Concealed tiles and
	// private claim responses belonging to other players are never included.
	GetMatchState(context.Context, *GetMatchStateRequest) (*GetMatchStateResponse, error)
	// SubmitMatchCommand applies one idempotent player command after validating
	// Session membership, seat ownership, turn ownership, and state version.
	SubmitMatchCommand(context.Context, *SubmitMatchCommandRequest) (*SubmitMatchCommandResponse, error)
}

// UnimplementedServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceServer struct{}

func (UnimplementedServiceServer) JoinMatch(context.Context, *JoinMatchRequest) (*JoinMatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinMatch not implemented")
}
func (UnimplementedServiceServer) GetMatchState(context.Context, *GetMatchStateRequest) (*GetMatchStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMatchState not implemented")
}
func (UnimplementedServiceServer) SubmitMatchCommand(context.Context, *SubmitMatchCommandRequest) (*SubmitMatchCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitMatchCommand not implemented")
}
func (UnimplementedServiceServer) testEmbeddedByValue() {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	// If the following call pancis, it indicates UnimplementedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_JoinMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).JoinMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_JoinMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).JoinMatch(ctx, req.(*JoinMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetMatchState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetMatchState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_GetMatchState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetMatchState(ctx, req.(*GetMatchStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_SubmitMatchCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitMatchCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).SubmitMatchCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_SubmitMatchCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).SubmitMatchCommand(ctx, req.(*SubmitMatchCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinMatch",
			Handler:    _Service_JoinMatch_Handler,
		},
		{
			MethodName: "GetMatchState",
			Handler:    _Service_GetMatchState_Handler,
		},
		{
			MethodName: "SubmitMatchCommand",
			Handler:    _Service_SubmitMatchCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
