// Copyright (c) 2023 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.9
// source: service.proto

package serviceextension

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchCommandType int32

const (
	MatchCommandType_MATCH_COMMAND_TYPE_UNSPECIFIED  MatchCommandType = 0
	MatchCommandType_MATCH_COMMAND_TYPE_DRAW         MatchCommandType = 1
	MatchCommandType_MATCH_COMMAND_TYPE_DISCARD      MatchCommandType = 2
	MatchCommandType_MATCH_COMMAND_TYPE_SUBMIT_CLAIM MatchCommandType = 3
)

// Enum value maps for MatchCommandType.
var (
	MatchCommandType_name = map[int32]string{
		0: "MATCH_COMMAND_TYPE_UNSPECIFIED",
		1: "MATCH_COMMAND_TYPE_DRAW",
		2: "MATCH_COMMAND_TYPE_DISCARD",
		3: "MATCH_COMMAND_TYPE_SUBMIT_CLAIM",
	}
	MatchCommandType_value = map[string]int32{
		"MATCH_COMMAND_TYPE_UNSPECIFIED":  0,
		"MATCH_COMMAND_TYPE_DRAW":         1,
		"MATCH_COMMAND_TYPE_DISCARD":      2,
		"MATCH_COMMAND_TYPE_SUBMIT_CLAIM": 3,
	}
)

func (x MatchCommandType) Enum() *MatchCommandType {
	p := new(MatchCommandType)
	*p = x
	return p
}

func (x MatchCommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchCommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[0].Descriptor()
}

func (MatchCommandType) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[0]
}

func (x MatchCommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchCommandType.Descriptor instead.
func (MatchCommandType) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

type JoinMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MatchId       string                 `protobuf:"bytes,3,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinMatchRequest) Reset() {
	*x = JoinMatchRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinMatchRequest) ProtoMessage() {}

func (x *JoinMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinMatchRequest.ProtoReflect.Descriptor instead.
func (*JoinMatchRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *JoinMatchRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *JoinMatchRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *JoinMatchRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

type JoinMatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *MatchState            `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinMatchResponse) Reset() {
	*x = JoinMatchResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinMatchResponse) ProtoMessage() {}

func (x *JoinMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinMatchResponse.ProtoReflect.Descriptor instead.
func (*JoinMatchResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *JoinMatchResponse) GetState() *MatchState {
	if x != nil {
		return x.State
	}
	return nil
}

type GetMatchStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MatchId       string                 `protobuf:"bytes,3,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchStateRequest) Reset() {
	*x = GetMatchStateRequest{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchStateRequest) ProtoMessage() {}

func (x *GetMatchStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchStateRequest.ProtoReflect.Descriptor instead.
func (*GetMatchStateRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetMatchStateRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetMatchStateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetMatchStateRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

type GetMatchStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *MatchState            `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchStateResponse) Reset() {
	*x = GetMatchStateResponse{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchStateResponse) ProtoMessage() {}

func (x *GetMatchStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchStateResponse.ProtoReflect.Descriptor instead.
func (*GetMatchStateResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetMatchStateResponse) GetState() *MatchState {
	if x != nil {
		return x.State
	}
	return nil
}

type SubmitMatchCommandRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Namespace       string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SessionId       string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MatchId         string                 `protobuf:"bytes,3,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	RequestId       string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Type            MatchCommandType       `protobuf:"varint,5,opt,name=type,proto3,enum=service.MatchCommandType" json:"type,omitempty"`
	ExpectedVersion uint64                 `protobuf:"varint,6,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	TileId          string                 `protobuf:"bytes,7,opt,name=tile_id,json=tileId,proto3" json:"tile_id,omitempty"`
	Claim           *ClaimCommand          `protobuf:"bytes,8,opt,name=claim,proto3" json:"claim,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubmitMatchCommandRequest) Reset() {
	*x = SubmitMatchCommandRequest{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitMatchCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitMatchCommandRequest) ProtoMessage() {}

func (x *SubmitMatchCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitMatchCommandRequest.ProtoReflect.Descriptor instead.
func (*SubmitMatchCommandRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitMatchCommandRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SubmitMatchCommandRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SubmitMatchCommandRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *SubmitMatchCommandRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SubmitMatchCommandRequest) GetType() MatchCommandType {
	if x != nil {
		return x.Type
	}
	return MatchCommandType_MATCH_COMMAND_TYPE_UNSPECIFIED
}

func (x *SubmitMatchCommandRequest) GetExpectedVersion() uint64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *SubmitMatchCommandRequest) GetTileId() string {
	if x != nil {
		return x.TileId
	}
	return ""
}

func (x *SubmitMatchCommandRequest) GetClaim() *ClaimCommand {
	if x != nil {
		return x.Claim
	}
	return nil
}

type ClaimCommand struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ActionId         string                 `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Type             string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	TileIds          []string               `protobuf:"bytes,3,rep,name=tile_ids,json=tileIds,proto3" json:"tile_ids,omitempty"`
	ResponseRevision uint64                 `protobuf:"varint,4,opt,name=response_revision,json=responseRevision,proto3" json:"response_revision,omitempty"`
	Deliberate       bool                   `protobuf:"varint,5,opt,name=deliberate,proto3" json:"deliberate,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClaimCommand) Reset() {
	*x = ClaimCommand{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimCommand) ProtoMessage() {}

func (x *ClaimCommand) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimCommand.ProtoReflect.Descriptor instead.
func (*ClaimCommand) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *ClaimCommand) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *ClaimCommand) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ClaimCommand) GetTileIds() []string {
	if x != nil {
		return x.TileIds
	}
	return nil
}

func (x *ClaimCommand) GetResponseRevision() uint64 {
	if x != nil {
		return x.ResponseRevision
	}
	return 0
}

func (x *ClaimCommand) GetDeliberate() bool {
	if x != nil {
		return x.Deliberate
	}
	return false
}

type SubmitMatchCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	StateVersion  uint64                 `protobuf:"varint,2,opt,name=state_version,json=stateVersion,proto3" json:"state_version,omitempty"`
	Phase         string                 `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	State         *MatchState            `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitMatchCommandResponse) Reset() {
	*x = SubmitMatchCommandResponse{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitMatchCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitMatchCommandResponse) ProtoMessage() {}

func (x *SubmitMatchCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitMatchCommandResponse.ProtoReflect.Descriptor instead.
func (*SubmitMatchCommandResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitMatchCommandResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SubmitMatchCommandResponse) GetStateVersion() uint64 {
	if x != nil {
		return x.StateVersion
	}
	return 0
}

func (x *SubmitMatchCommandResponse) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *SubmitMatchCommandResponse) GetState() *MatchState {
	if x != nil {
		return x.State
	}
	return nil
}

// MatchState is a privacy-filtered projection for exactly one authenticated
// player. It is not a serializable authoritative snapshot.
type MatchState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Seat          string                 `protobuf:"bytes,2,opt,name=seat,proto3" json:"seat,omitempty"`
	StateVersion  uint64                 `protobuf:"varint,3,opt,name=state_version,json=stateVersion,proto3" json:"state_version,omitempty"`
	Phase         string                 `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	ActiveSeat    string                 `protobuf:"bytes,5,opt,name=active_seat,json=activeSeat,proto3" json:"active_seat,omitempty"`
	OwnHand       []*Tile                `protobuf:"bytes,6,rep,name=own_hand,json=ownHand,proto3" json:"own_hand,omitempty"`
	OwnExposed    []*Tile                `protobuf:"bytes,7,rep,name=own_exposed,json=ownExposed,proto3" json:"own_exposed,omitempty"`
	Players       []*PlayerView          `protobuf:"bytes,8,rep,name=players,proto3" json:"players,omitempty"`
	Wall          *WallView              `protobuf:"bytes,9,opt,name=wall,proto3" json:"wall,omitempty"`
	LastDiscard   *Discard               `protobuf:"bytes,10,opt,name=last_discard,json=lastDiscard,proto3" json:"last_discard,omitempty"`
	Claim         *ClaimView             `protobuf:"bytes,11,opt,name=claim,proto3" json:"claim,omitempty"`
	WinLocked     bool                   `protobuf:"varint,12,opt,name=win_locked,json=winLocked,proto3" json:"win_locked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchState) Reset() {
	*x = MatchState{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchState) ProtoMessage() {}

func (x *MatchState) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchState.ProtoReflect.Descriptor instead.
func (*MatchState) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *MatchState) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchState) GetSeat() string {
	if x != nil {
		return x.Seat
	}
	return ""
}

func (x *MatchState) GetStateVersion() uint64 {
	if x != nil {
		return x.StateVersion
	}
	return 0
}

func (x *MatchState) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *MatchState) GetActiveSeat() string {
	if x != nil {
		return x.ActiveSeat
	}
	return ""
}

func (x *MatchState) GetOwnHand() []*Tile {
	if x != nil {
		return x.OwnHand
	}
	return nil
}

func (x *MatchState) GetOwnExposed() []*Tile {
	if x != nil {
		return x.OwnExposed
	}
	return nil
}

func (x *MatchState) GetPlayers() []*PlayerView {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *MatchState) GetWall() *WallView {
	if x != nil {
		return x.Wall
	}
	return nil
}

func (x *MatchState) GetLastDiscard() *Discard {
	if x != nil {
		return x.LastDiscard
	}
	return nil
}

func (x *MatchState) GetClaim() *ClaimView {
	if x != nil {
		return x.Claim
	}
	return nil
}

func (x *MatchState) GetWinLocked() bool {
	if x != nil {
		return x.WinLocked
	}
	return false
}

type Tile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Rank          uint32                 `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	Copy          uint32                 `protobuf:"varint,4,opt,name=copy,proto3" json:"copy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tile) Reset() {
	*x = Tile{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tile) ProtoMessage() {}

func (x *Tile) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tile.ProtoReflect.Descriptor instead.
func (*Tile) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *Tile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tile) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Tile) GetRank() uint32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *Tile) GetCopy() uint32 {
	if x != nil {
		return x.Copy
	}
	return 0
}

type PlayerView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seat          string                 `protobuf:"bytes,1,opt,name=seat,proto3" json:"seat,omitempty"`
	HandCount     int32                  `protobuf:"varint,2,opt,name=hand_count,json=handCount,proto3" json:"hand_count,omitempty"`
	Exposed       []*Tile                `protobuf:"bytes,3,rep,name=exposed,proto3" json:"exposed,omitempty"`
	MeldCount     int32                  `protobuf:"varint,4,opt,name=meld_count,json=meldCount,proto3" json:"meld_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerView) Reset() {
	*x = PlayerView{}
	mi := &file_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerView) ProtoMessage() {}

func (x *PlayerView) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerView.ProtoReflect.Descriptor instead.
func (*PlayerView) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerView) GetSeat() string {
	if x != nil {
		return x.Seat
	}
	return ""
}

func (x *PlayerView) GetHandCount() int32 {
	if x != nil {
		return x.HandCount
	}
	return 0
}

func (x *PlayerView) GetExposed() []*Tile {
	if x != nil {
		return x.Exposed
	}
	return nil
}

func (x *PlayerView) GetMeldCount() int32 {
	if x != nil {
		return x.MeldCount
	}
	return 0
}

type WallView struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Remaining         int32                  `protobuf:"varint,1,opt,name=remaining,proto3" json:"remaining,omitempty"`
	DrawableRemaining int32                  `protobuf:"varint,2,opt,name=drawable_remaining,json=drawableRemaining,proto3" json:"drawable_remaining,omitempty"`
	ReserveRemaining  int32                  `protobuf:"varint,3,opt,name=reserve_remaining,json=reserveRemaining,proto3" json:"reserve_remaining,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WallView) Reset() {
	*x = WallView{}
	mi := &file_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WallView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WallView) ProtoMessage() {}

func (x *WallView) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WallView.ProtoReflect.Descriptor instead.
func (*WallView) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{10}
}

func (x *WallView) GetRemaining() int32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *WallView) GetDrawableRemaining() int32 {
	if x != nil {
		return x.DrawableRemaining
	}
	return 0
}

func (x *WallView) GetReserveRemaining() int32 {
	if x != nil {
		return x.ReserveRemaining
	}
	return 0
}

type Discard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seat          string                 `protobuf:"bytes,1,opt,name=seat,proto3" json:"seat,omitempty"`
	Tile          *Tile                  `protobuf:"bytes,2,opt,name=tile,proto3" json:"tile,omitempty"`
	Sequence      uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Discard) Reset() {
	*x = Discard{}
	mi := &file_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Discard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Discard) ProtoMessage() {}

func (x *Discard) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Discard.ProtoReflect.Descriptor instead.
func (*Discard) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{11}
}

func (x *Discard) GetSeat() string {
	if x != nil {
		return x.Seat
	}
	return ""
}

func (x *Discard) GetTile() *Tile {
	if x != nil {
		return x.Tile
	}
	return nil
}

func (x *Discard) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type ClaimView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionId      string                 `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	StateVersion  uint64                 `protobuf:"varint,2,opt,name=state_version,json=stateVersion,proto3" json:"state_version,omitempty"`
	Discard       *Discard               `protobuf:"bytes,3,opt,name=discard,proto3" json:"discard,omitempty"`
	Deadline      string                 `protobuf:"bytes,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Eligible      []string               `protobuf:"bytes,5,rep,name=eligible,proto3" json:"eligible,omitempty"`
	OwnResponse   *ClaimResponse         `protobuf:"bytes,6,opt,name=own_response,json=ownResponse,proto3" json:"own_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimView) Reset() {
	*x = ClaimView{}
	mi := &file_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimView) ProtoMessage() {}

func (x *ClaimView) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimView.ProtoReflect.Descriptor instead.
func (*ClaimView) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{12}
}

func (x *ClaimView) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *ClaimView) GetStateVersion() uint64 {
	if x != nil {
		return x.StateVersion
	}
	return 0
}

func (x *ClaimView) GetDiscard() *Discard {
	if x != nil {
		return x.Discard
	}
	return nil
}

func (x *ClaimView) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

func (x *ClaimView) GetEligible() []string {
	if x != nil {
		return x.Eligible
	}
	return nil
}

func (x *ClaimView) GetOwnResponse() *ClaimResponse {
	if x != nil {
		return x.OwnResponse
	}
	return nil
}

type ClaimResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ActionId         string                 `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Seat             string                 `protobuf:"bytes,2,opt,name=seat,proto3" json:"seat,omitempty"`
	Type             string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	TileIds          []string               `protobuf:"bytes,4,rep,name=tile_ids,json=tileIds,proto3" json:"tile_ids,omitempty"`
	StateVersion     uint64                 `protobuf:"varint,5,opt,name=state_version,json=stateVersion,proto3" json:"state_version,omitempty"`
	ResponseRevision uint64                 `protobuf:"varint,6,opt,name=response_revision,json=responseRevision,proto3" json:"response_revision,omitempty"`
	Deliberate       bool                   `protobuf:"varint,7,opt,name=deliberate,proto3" json:"deliberate,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClaimResponse) Reset() {
	*x = ClaimResponse{}
	mi := &file_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimResponse) ProtoMessage() {}

func (x *ClaimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimResponse.ProtoReflect.Descriptor instead.
func (*ClaimResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{13}
}

func (x *ClaimResponse) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *ClaimResponse) GetSeat() string {
	if x != nil {
		return x.Seat
	}
	return ""
}

func (x *ClaimResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ClaimResponse) GetTileIds() []string {
	if x != nil {
		return x.TileIds
	}
	return nil
}

func (x *ClaimResponse) GetStateVersion() uint64 {
	if x != nil {
		return x.StateVersion
	}
	return 0
}

func (x *ClaimResponse) GetResponseRevision() uint64 {
	if x != nil {
		return x.ResponseRevision
	}
	return 0
}

func (x *ClaimResponse) GetDeliberate() bool {
	if x != nil {
		return x.Deliberate
	}
	return false
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\aservice\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"j\n" +
	"\x10JoinMatchRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x19\n" +
	"\bmatch_id\x18\x03 \x01(\tR\amatchId\">\n" +
	"\x11JoinMatchResponse\x12)\n" +
	"\x05state\x18\x01 \x01(\v2\x13.service.MatchStateR\x05state\"n\n" +
	"\x14GetMatchStateRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x19\n" +
	"\bmatch_id\x18\x03 \x01(\tR\amatchId\"B\n" +
	"\x15GetMatchStateResponse\x12)\n" +
	"\x05state\x18\x01 \x01(\v2\x13.service.MatchStateR\x05state\"\xb2\x02\n" +
	"\x19SubmitMatchCommandRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x19\n" +
	"\bmatch_id\x18\x03 \x01(\tR\amatchId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12-\n" +
	"\x04type\x18\x05 \x01(\x0e2\x19.service.MatchCommandTypeR\x04type\x12)\n" +
	"\x10expected_version\x18\x06 \x01(\x04R\x0fexpectedVersion\x12\x17\n" +
	"\atile_id\x18\a \x01(\tR\x06tileId\x12+\n" +
	"\x05claim\x18\b \x01(\v2\x15.service.ClaimCommandR\x05claim\"\xa7\x01\n" +
	"\fClaimCommand\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\tR\bactionId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x19\n" +
	"\btile_ids\x18\x03 \x03(\tR\atileIds\x12+\n" +
	"\x11response_revision\x18\x04 \x01(\x04R\x10responseRevision\x12\x1e\n" +
	"\n" +
	"deliberate\x18\x05 \x01(\bR\n" +
	"deliberate\"\xa1\x01\n" +
	"\x1aSubmitMatchCommandResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12#\n" +
	"\rstate_version\x18\x02 \x01(\x04R\fstateVersion\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\x12)\n" +
	"\x05state\x18\x04 \x01(\v2\x13.service.MatchStateR\x05state\"\xc5\x03\n" +
	"\n" +
	"MatchState\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x12\n" +
	"\x04seat\x18\x02 \x01(\tR\x04seat\x12#\n" +
	"\rstate_version\x18\x03 \x01(\x04R\fstateVersion\x12\x14\n" +
	"\x05phase\x18\x04 \x01(\tR\x05phase\x12\x1f\n" +
	"\vactive_seat\x18\x05 \x01(\tR\n" +
	"activeSeat\x12(\n" +
	"\bown_hand\x18\x06 \x03(\v2\r.service.TileR\aownHand\x12.\n" +
	"\vown_exposed\x18\a \x03(\v2\r.service.TileR\n" +
	"ownExposed\x12-\n" +
	"\aplayers\x18\b \x03(\v2\x13.service.PlayerViewR\aplayers\x12%\n" +
	"\x04wall\x18\t \x01(\v2\x11.service.WallViewR\x04wall\x123\n" +
	"\flast_discard\x18\n" +
	" \x01(\v2\x10.service.DiscardR\vlastDiscard\x12(\n" +
	"\x05claim\x18\v \x01(\v2\x12.service.ClaimViewR\x05claim\x12\x1d\n" +
	"\n" +
	"win_locked\x18\f \x01(\bR\twinLocked\"R\n" +
	"\x04Tile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04rank\x18\x03 \x01(\rR\x04rank\x12\x12\n" +
	"\x04copy\x18\x04 \x01(\rR\x04copy\"\x87\x01\n" +
	"\n" +
	"PlayerView\x12\x12\n" +
	"\x04seat\x18\x01 \x01(\tR\x04seat\x12\x1d\n" +
	"\n" +
	"hand_count\x18\x02 \x01(\x05R\thandCount\x12'\n" +
	"\aexposed\x18\x03 \x03(\v2\r.service.TileR\aexposed\x12\x1d\n" +
	"\n" +
	"meld_count\x18\x04 \x01(\x05R\tmeldCount\"\x84\x01\n" +
	"\bWallView\x12\x1c\n" +
	"\tremaining\x18\x01 \x01(\x05R\tremaining\x12-\n" +
	"\x12drawable_remaining\x18\x02 \x01(\x05R\x11drawableRemaining\x12+\n" +
	"\x11reserve_remaining\x18\x03 \x01(\x05R\x10reserveRemaining\"\\\n" +
	"\aDiscard\x12\x12\n" +
	"\x04seat\x18\x01 \x01(\tR\x04seat\x12!\n" +
	"\x04tile\x18\x02 \x01(\v2\r.service.TileR\x04tile\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\"\xec\x01\n" +
	"\tClaimView\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\tR\bactionId\x12#\n" +
	"\rstate_version\x18\x02 \x01(\x04R\fstateVersion\x12*\n" +
	"\adiscard\x18\x03 \x01(\v2\x10.service.DiscardR\adiscard\x12\x1a\n" +
	"\bdeadline\x18\x04 \x01(\tR\bdeadline\x12\x1a\n" +
	"\beligible\x18\x05 \x03(\tR\beligible\x129\n" +
	"\fown_response\x18\x06 \x01(\v2\x16.service.ClaimResponseR\vownResponse\"\xe1\x01\n" +
	"\rClaimResponse\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\tR\bactionId\x12\x12\n" +
	"\x04seat\x18\x02 \x01(\tR\x04seat\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x19\n" +
	"\btile_ids\x18\x04 \x03(\tR\atileIds\x12#\n" +
	"\rstate_version\x18\x05 \x01(\x04R\fstateVersion\x12+\n" +
	"\x11response_revision\x18\x06 \x01(\x04R\x10responseRevision\x12\x1e\n" +
	"\n" +
	"deliberate\x18\a \x01(\bR\n" +
	"deliberate*\x98\x01\n" +
	"\x10MatchCommandType\x12\"\n" +
	"\x1eMATCH_COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17MATCH_COMMAND_TYPE_DRAW\x10\x01\x12\x1e\n" +
	"\x1aMATCH_COMMAND_TYPE_DISCARD\x10\x02\x12#\n" +
	"\x1fMATCH_COMMAND_TYPE_SUBMIT_CLAIM\x10\x032\x83\b\n" +
	"\aService\x12\xcb\x02\n" +
	"\tJoinMatch\x12\x19.service.JoinMatchRequest\x1a\x1a.service.JoinMatchResponse\"\x86\x02\x92A\xaf\x01\x12#Join an authoritative Mahjong match\x1azCreates the match from the fixed AGS Session roster when needed and returns the authenticated player's private projection.b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02M:\x01*\"H/v1/namespaces/{namespace}/sessions/{session_id}/matches/{match_id}/join\x12\xba\x02\n" +
	"\rGetMatchState\x12\x1d.service.GetMatchStateRequest\x1a\x1e.service.GetMatchStateResponse\"\xe9\x01\x92A\x9a\x01\x12*Get the authenticated player's match state\x1a^Returns the latest authoritative match projection visible to the authenticated Session member.b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02E\x12C/v1/namespaces/{namespace}/sessions/{session_id}/matches/{match_id}\x12\xec\x02\n" +
	"\x12SubmitMatchCommand\x12\".service.SubmitMatchCommandRequest\x1a#.service.SubmitMatchCommandResponse\"\x8c\x02\x92A\xb1\x01\x12'Submit an authoritative Mahjong command\x1axDurably applies an idempotent draw, discard, or claim command and returns the authenticated player's updated projection.b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02Q:\x01*\"L/v1/namespaces/{namespace}/sessions/{session_id}/matches/{match_id}/commandsB\xc3\x01\x92AL\x12\x1f\n" +
	"\x19Mahjong Match Service API2\x02v1\"\b/mahjongZ\x1f\n" +
	"\x1d\n" +
	"\x06Bearer\x12\x13\b\x02\x1a\rAuthorization \x02\n" +
	"%net.accelbyte.extend.serviceextensionP\x01Z%accelbyte.net/extend/serviceextension\xaa\x02!AccelByte.Extend.ServiceExtensionb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_service_proto_goTypes = []any{
	(MatchCommandType)(0),              // 0: service.MatchCommandType
	(*JoinMatchRequest)(nil),           // 1: service.JoinMatchRequest
	(*JoinMatchResponse)(nil),          // 2: service.JoinMatchResponse
	(*GetMatchStateRequest)(nil),       // 3: service.GetMatchStateRequest
	(*GetMatchStateResponse)(nil),      // 4: service.GetMatchStateResponse
	(*SubmitMatchCommandRequest)(nil),  // 5: service.SubmitMatchCommandRequest
	(*ClaimCommand)(nil),               // 6: service.ClaimCommand
	(*SubmitMatchCommandResponse)(nil), // 7: service.SubmitMatchCommandResponse
	(*MatchState)(nil),                 // 8: service.MatchState
	(*Tile)(nil),                       // 9: service.Tile
	(*PlayerView)(nil),                 // 10: service.PlayerView
	(*WallView)(nil),                   // 11: service.WallView
	(*Discard)(nil),                    // 12: service.Discard
	(*ClaimView)(nil),                  // 13: service.ClaimView
	(*ClaimResponse)(nil),              // 14: service.ClaimResponse
}
var file_service_proto_depIdxs = []int32{
	8,  // 0: service.JoinMatchResponse.state:type_name -> service.MatchState
	8,  // 1: service.GetMatchStateResponse.state:type_name -> service.MatchState
	0,  // 2: service.SubmitMatchCommandRequest.type:type_name -> service.MatchCommandType
	6,  // 3: service.SubmitMatchCommandRequest.claim:type_name -> service.ClaimCommand
	8,  // 4: service.SubmitMatchCommandResponse.state:type_name -> service.MatchState
	9,  // 5: service.MatchState.own_hand:type_name -> service.Tile
	9,  // 6: service.MatchState.own_exposed:type_name -> service.Tile
	10, // 7: service.MatchState.players:type_name -> service.PlayerView
	11, // 8: service.MatchState.wall:type_name -> service.WallView
	12, // 9: service.MatchState.last_discard:type_name -> service.Discard
	13, // 10: service.MatchState.claim:type_name -> service.ClaimView
	9,  // 11: service.PlayerView.exposed:type_name -> service.Tile
	9,  // 12: service.Discard.tile:type_name -> service.Tile
	12, // 13: service.ClaimView.discard:type_name -> service.Discard
	14, // 14: service.ClaimView.own_response:type_name -> service.ClaimResponse
	1,  // 15: service.Service.JoinMatch:input_type -> service.JoinMatchRequest
	3,  // 16: service.Service.GetMatchState:input_type -> service.GetMatchStateRequest
	5,  // 17: service.Service.SubmitMatchCommand:input_type -> service.SubmitMatchCommandRequest
	2,  // 18: service.Service.JoinMatch:output_type -> service.JoinMatchResponse
	4,  // 19: service.Service.GetMatchState:output_type -> service.GetMatchStateResponse
	7,  // 20: service.Service.SubmitMatchCommand:output_type -> service.SubmitMatchCommandResponse
	18, // [18:21] is the sub-list for method output_type
	15, // [15:18] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		EnumInfos:         file_service_proto_enumTypes,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
