// Copyright (c) 2023 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: service.proto

package serviceextension

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Service_GetJadeAccount_FullMethodName        = "/service.Service/GetJadeAccount"
	Service_ReserveJade_FullMethodName           = "/service.Service/ReserveJade"
	Service_ReleaseJade_FullMethodName           = "/service.Service/ReleaseJade"
	Service_ClaimJadeWelfare_FullMethodName      = "/service.Service/ClaimJadeWelfare"
	Service_GetProgression_FullMethodName        = "/service.Service/GetProgression"
	Service_AwardOnboardingXP_FullMethodName     = "/service.Service/AwardOnboardingXP"
	Service_GetPlayerStatistics_FullMethodName   = "/service.Service/GetPlayerStatistics"
	Service_GetMatchHistory_FullMethodName       = "/service.Service/GetMatchHistory"
	Service_GetPlayerAchievements_FullMethodName = "/service.Service/GetPlayerAchievements"
	Service_ListBotPersonas_FullMethodName       = "/service.Service/ListBotPersonas"
	Service_JoinMatch_FullMethodName             = "/service.Service/JoinMatch"
	Service_GetMatchState_FullMethodName         = "/service.Service/GetMatchState"
	Service_SubmitMatchCommand_FullMethodName    = "/service.Service/SubmitMatchCommand"
)

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	GetJadeAccount(ctx context.Context, in *GetJadeAccountRequest, opts ...grpc.CallOption) (*GetJadeAccountResponse, error)
	ReserveJade(ctx context.Context, in *ReserveJadeRequest, opts ...grpc.CallOption) (*ReserveJadeResponse, error)
	ReleaseJade(ctx context.Context, in *ReleaseJadeRequest, opts ...grpc.CallOption) (*ReleaseJadeResponse, error)
	ClaimJadeWelfare(ctx context.Context, in *ClaimJadeWelfareRequest, opts ...grpc.CallOption) (*ClaimJadeWelfareResponse, error)
	GetProgression(ctx context.Context, in *GetProgressionRequest, opts ...grpc.CallOption) (*GetProgressionResponse, error)
	AwardOnboardingXP(ctx context.Context, in *AwardOnboardingXPRequest, opts ...grpc.CallOption) (*AwardOnboardingXPResponse, error)
	// JoinMatch creates the authoritative match from the fixed AGS Session
	// roster when necessary, assigns stable seats, and returns only the
	// authenticated caller's view.
	GetPlayerStatistics(ctx context.Context, in *GetPlayerStatisticsRequest, opts ...grpc.CallOption) (*GetPlayerStatisticsResponse, error)
	GetMatchHistory(ctx context.Context, in *GetMatchHistoryRequest, opts ...grpc.CallOption) (*GetMatchHistoryResponse, error)
	GetPlayerAchievements(ctx context.Context, in *GetPlayerAchievementsRequest, opts ...grpc.CallOption) (*GetPlayerAchievementsResponse, error)
	ListBotPersonas(ctx context.Context, in *ListBotPersonasRequest, opts ...grpc.CallOption) (*ListBotPersonasResponse, error)
	JoinMatch(ctx context.Context, in *JoinMatchRequest, opts ...grpc.CallOption) (*JoinMatchResponse, error)
	// GetMatchState returns a caller-specific projection. Concealed tiles and
	// private claim responses belonging to other players are never included.
	GetMatchState(ctx context.Context, in *GetMatchStateRequest, opts ...grpc.CallOption) (*GetMatchStateResponse, error)
	// SubmitMatchCommand applies one idempotent player command after validating
	// Session membership, seat ownership, turn ownership, and state version.
	SubmitMatchCommand(ctx context.Context, in *SubmitMatchCommandRequest, opts ...grpc.CallOption) (*SubmitMatchCommandResponse, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) GetJadeAccount(ctx context.Context, in *GetJadeAccountRequest, opts ...grpc.CallOption) (*GetJadeAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJadeAccountResponse)
	err := c.cc.Invoke(ctx, Service_GetJadeAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ReserveJade(ctx context.Context, in *ReserveJadeRequest, opts ...grpc.CallOption) (*ReserveJadeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveJadeResponse)
	err := c.cc.Invoke(ctx, Service_ReserveJade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ReleaseJade(ctx context.Context, in *ReleaseJadeRequest, opts ...grpc.CallOption) (*ReleaseJadeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseJadeResponse)
	err := c.cc.Invoke(ctx, Service_ReleaseJade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ClaimJadeWelfare(ctx context.Context, in *ClaimJadeWelfareRequest, opts ...grpc.CallOption) (*ClaimJadeWelfareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimJadeWelfareResponse)
	err := c.cc.Invoke(ctx, Service_ClaimJadeWelfare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetProgression(ctx context.Context, in *GetProgressionRequest, opts ...grpc.CallOption) (*GetProgressionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProgressionResponse)
	err := c.cc.Invoke(ctx, Service_GetProgression_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) AwardOnboardingXP(ctx context.Context, in *AwardOnboardingXPRequest, opts ...grpc.CallOption) (*AwardOnboardingXPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AwardOnboardingXPResponse)
	err := c.cc.Invoke(ctx, Service_AwardOnboardingXP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetPlayerStatistics(ctx context.Context, in *GetPlayerStatisticsRequest, opts ...grpc.CallOption) (*GetPlayerStatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlayerStatisticsResponse)
	err := c.cc.Invoke(ctx, Service_GetPlayerStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetMatchHistory(ctx context.Context, in *GetMatchHistoryRequest, opts ...grpc.CallOption) (*GetMatchHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMatchHistoryResponse)
	err := c.cc.Invoke(ctx, Service_GetMatchHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetPlayerAchievements(ctx context.Context, in *GetPlayerAchievementsRequest, opts ...grpc.CallOption) (*GetPlayerAchievementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlayerAchievementsResponse)
	err := c.cc.Invoke(ctx, Service_GetPlayerAchievements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ListBotPersonas(ctx context.Context, in *ListBotPersonasRequest, opts ...grpc.CallOption) (*ListBotPersonasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBotPersonasResponse)
	err := c.cc.Invoke(ctx, Service_ListBotPersonas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) JoinMatch(ctx context.Context, in *JoinMatchRequest, opts ...grpc.CallOption) (*JoinMatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinMatchResponse)
	err := c.cc.Invoke(ctx, Service_JoinMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetMatchState(ctx context.Context, in *GetMatchStateRequest, opts ...grpc.CallOption) (*GetMatchStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMatchStateResponse)
	err := c.cc.Invoke(ctx, Service_GetMatchState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) SubmitMatchCommand(ctx context.Context, in *SubmitMatchCommandRequest, opts ...grpc.CallOption) (*SubmitMatchCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitMatchCommandResponse)
	err := c.cc.Invoke(ctx, Service_SubmitMatchCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations should embed UnimplementedServiceServer
// for forward compatibility.
type ServiceServer interface {
	GetJadeAccount(context.Context, *GetJadeAccountRequest) (*GetJadeAccountResponse, error)
	ReserveJade(context.Context, *ReserveJadeRequest) (*ReserveJadeResponse, error)
	ReleaseJade(context.Context, *ReleaseJadeRequest) (*ReleaseJadeResponse, error)
	ClaimJadeWelfare(context.Context, *ClaimJadeWelfareRequest) (*ClaimJadeWelfareResponse, error)
	GetProgression(context.Context, *GetProgressionRequest) (*GetProgressionResponse, error)
	AwardOnboardingXP(context.Context, *AwardOnboardingXPRequest) (*AwardOnboardingXPResponse, error)
	// JoinMatch creates the authoritative match from the fixed AGS Session
	// roster when necessary, assigns stable seats, and returns only the
	// authenticated caller's view.
	GetPlayerStatistics(context.Context, *GetPlayerStatisticsRequest) (*GetPlayerStatisticsResponse, error)
	GetMatchHistory(context.Context, *GetMatchHistoryRequest) (*GetMatchHistoryResponse, error)
	GetPlayerAchievements(context.Context, *GetPlayerAchievementsRequest) (*GetPlayerAchievementsResponse, error)
	ListBotPersonas(context.Context, *ListBotPersonasRequest) (*ListBotPersonasResponse, error)
	JoinMatch(context.Context, *JoinMatchRequest) (*JoinMatchResponse, error)
	// GetMatchState returns a caller-specific projection. Concealed tiles and
	// private claim responses belonging to other players are never included.
	GetMatchState(context.Context, *GetMatchStateRequest) (*GetMatchStateResponse, error)
	// SubmitMatchCommand applies one idempotent player command after validating
	// Session membership, seat ownership, turn ownership, and state version.
	SubmitMatchCommand(context.Context, *SubmitMatchCommandRequest) (*SubmitMatchCommandResponse, error)
}

// UnimplementedServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceServer struct{}

func (UnimplementedServiceServer) GetJadeAccount(context.Context, *GetJadeAccountRequest) (*GetJadeAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJadeAccount not implemented")
}
func (UnimplementedServiceServer) ReserveJade(context.Context, *ReserveJadeRequest) (*ReserveJadeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveJade not implemented")
}
func (UnimplementedServiceServer) ReleaseJade(context.Context, *ReleaseJadeRequest) (*ReleaseJadeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseJade not implemented")
}
func (UnimplementedServiceServer) ClaimJadeWelfare(context.Context, *ClaimJadeWelfareRequest) (*ClaimJadeWelfareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimJadeWelfare not implemented")
}
func (UnimplementedServiceServer) GetProgression(context.Context, *GetProgressionRequest) (*GetProgressionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProgression not implemented")
}
func (UnimplementedServiceServer) AwardOnboardingXP(context.Context, *AwardOnboardingXPRequest) (*AwardOnboardingXPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AwardOnboardingXP not implemented")
}
func (UnimplementedServiceServer) GetPlayerStatistics(context.Context, *GetPlayerStatisticsRequest) (*GetPlayerStatisticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlayerStatistics not implemented")
}
func (UnimplementedServiceServer) GetMatchHistory(context.Context, *GetMatchHistoryRequest) (*GetMatchHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMatchHistory not implemented")
}
func (UnimplementedServiceServer) GetPlayerAchievements(context.Context, *GetPlayerAchievementsRequest) (*GetPlayerAchievementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlayerAchievements not implemented")
}
func (UnimplementedServiceServer) ListBotPersonas(context.Context, *ListBotPersonasRequest) (*ListBotPersonasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBotPersonas not implemented")
}
func (UnimplementedServiceServer) JoinMatch(context.Context, *JoinMatchRequest) (*JoinMatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinMatch not implemented")
}
func (UnimplementedServiceServer) GetMatchState(context.Context, *GetMatchStateRequest) (*GetMatchStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMatchState not implemented")
}
func (UnimplementedServiceServer) SubmitMatchCommand(context.Context, *SubmitMatchCommandRequest) (*SubmitMatchCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitMatchCommand not implemented")
}
func (UnimplementedServiceServer) testEmbeddedByValue() {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	// If the following call panics, it indicates UnimplementedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_GetJadeAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJadeAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetJadeAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_GetJadeAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetJadeAccount(ctx, req.(*GetJadeAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ReserveJade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveJadeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ReserveJade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_ReserveJade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ReserveJade(ctx, req.(*ReserveJadeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ReleaseJade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseJadeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ReleaseJade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_ReleaseJade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ReleaseJade(ctx, req.(*ReleaseJadeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ClaimJadeWelfare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimJadeWelfareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ClaimJadeWelfare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_ClaimJadeWelfare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ClaimJadeWelfare(ctx, req.(*ClaimJadeWelfareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetProgression_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProgressionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetProgression(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_GetProgression_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetProgression(ctx, req.(*GetProgressionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_AwardOnboardingXP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AwardOnboardingXPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).AwardOnboardingXP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_AwardOnboardingXP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).AwardOnboardingXP(ctx, req.(*AwardOnboardingXPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetPlayerStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetPlayerStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_GetPlayerStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetPlayerStatistics(ctx, req.(*GetPlayerStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetMatchHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetMatchHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_GetMatchHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetMatchHistory(ctx, req.(*GetMatchHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetPlayerAchievements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerAchievementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetPlayerAchievements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_GetPlayerAchievements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetPlayerAchievements(ctx, req.(*GetPlayerAchievementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ListBotPersonas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBotPersonasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ListBotPersonas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_ListBotPersonas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ListBotPersonas(ctx, req.(*ListBotPersonasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_JoinMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).JoinMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_JoinMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).JoinMatch(ctx, req.(*JoinMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetMatchState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetMatchState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_GetMatchState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetMatchState(ctx, req.(*GetMatchStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_SubmitMatchCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitMatchCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).SubmitMatchCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_SubmitMatchCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).SubmitMatchCommand(ctx, req.(*SubmitMatchCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetJadeAccount",
			Handler:    _Service_GetJadeAccount_Handler,
		},
		{
			MethodName: "ReserveJade",
			Handler:    _Service_ReserveJade_Handler,
		},
		{
			MethodName: "ReleaseJade",
			Handler:    _Service_ReleaseJade_Handler,
		},
		{
			MethodName: "ClaimJadeWelfare",
			Handler:    _Service_ClaimJadeWelfare_Handler,
		},
		{
			MethodName: "GetProgression",
			Handler:    _Service_GetProgression_Handler,
		},
		{
			MethodName: "AwardOnboardingXP",
			Handler:    _Service_AwardOnboardingXP_Handler,
		},
		{
			MethodName: "GetPlayerStatistics",
			Handler:    _Service_GetPlayerStatistics_Handler,
		},
		{
			MethodName: "GetMatchHistory",
			Handler:    _Service_GetMatchHistory_Handler,
		},
		{
			MethodName: "GetPlayerAchievements",
			Handler:    _Service_GetPlayerAchievements_Handler,
		},
		{
			MethodName: "ListBotPersonas",
			Handler:    _Service_ListBotPersonas_Handler,
		},
		{
			MethodName: "JoinMatch",
			Handler:    _Service_JoinMatch_Handler,
		},
		{
			MethodName: "GetMatchState",
			Handler:    _Service_GetMatchState_Handler,
		},
		{
			MethodName: "SubmitMatchCommand",
			Handler:    _Service_SubmitMatchCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
